# Generated by Django 4.2.2 on 2023-09-02 19:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('specialization', models.CharField(max_length=100)),
                ('passwordHash', models.CharField(max_length=64)),
                ('emailHash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicineName', models.CharField(max_length=200)),
                ('beforeAfter', models.CharField(max_length=200)),
                ('Morning', models.CharField(max_length=200)),
                ('Afternoon', models.CharField(max_length=200)),
                ('Night', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('rollNumber', models.CharField(max_length=8)),
                ('passwordHash', models.CharField(max_length=64)),
                ('emailHash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescriptionText', models.CharField(default='', max_length=2000)),
                ('prescribingDoctor', models.CharField(default='', max_length=2000)),
                ('prescribingPatient', models.CharField(default='', max_length=2000)),
                ('NoOfDays', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isNew', models.BooleanField(default=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('symptoms', models.CharField(max_length=2000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorRecords', to='HealthCentre.doctor')),
                ('medicine', models.ManyToManyField(to='HealthCentre.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientRecords', to='HealthCentre.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=2000)),
                ('notes', models.TextField()),
                ('appointmentpatient', models.CharField(default='', max_length=2000)),
                ('appointmentdoctor', models.CharField(default='', max_length=2000)),
                ('AppointmentTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('doctorPres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorPrescRecords', to='HealthCentre.doctor')),
                ('patientPres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientPrescRecords', to='HealthCentre.patient')),
            ],
        ),
    ]
