# Generated by Django 4.2.2 on 2023-09-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0004_alter_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
