# Generated by Django 4.2.2 on 2023-08-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0028_remove_prescription_medicine_prescription_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='rollNumber',
            field=models.CharField(max_length=8),
        ),
    ]
