# Generated by Django 4.2.2 on 2023-08-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0030_alter_prescription_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
